
server:
  port: 8082

spring:
  datasource:
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/order_service_db
    username: postgres

  application:
    name: ORDER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

